<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the commercial license
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category Extait
 * @package Extait_ZendeskChat
 * @copyright Copyright (c) 2016-2018 Extait, Inc. (http://www.extait.com)
 */

// @codingStandardsIgnoreFile

/** @var \Extait\ZendeskChat\Block\ZendeskChat $block */
?>

<?= /* @escapeNotVerified */ $block->getZendeskChatScript() ?>
